spring:
  threads:
    virtual:
      enabled: true
  application:
    name: demo
  cloud:
    function:
      definition: testConsumer
    stream:
      bindings:
        test-out-0:
          destination: my-topic
        testConsumer-in-0:
          destination: my-topic
          group: spring-group
          consumer:
            max-attempts: 5
            back-off-initial-interval: 5000 # Espera 5s entre tentativas
            back-off-max-interval: 30000    # No m√°ximo espera 30 segundos
            back-off-multiplier: 2.0

      kafka:
        bindings:
          testConsumer-in-0:
            consumer:
              enable-dlq: true
server:
  port: 8082